# Generated by Django 5.1.5 on 2025-02-11 09:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rfid_tag', models.CharField(max_length=100, unique=True)),
                ('rfid_tag_description', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('NONE', 'None'), ('ASSIGNED', 'Assigned'), ('NOT ASSIGNED', 'Not Assigned')], default='NONE', max_length=20)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('rfid_tag', models.CharField(max_length=255, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('action', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=10)),
                ('timestamp_in', models.DateTimeField(auto_now_add=True)),
                ('timestamp_out', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('assigned_rfid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database_admin.rfidentry')),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='database_ad_categor_193b31_idx')],
            },
        ),
    ]
