# Generated by Django 5.1.5 on 2025-02-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='assigned_rfid',
            new_name='assign_rfid',
        ),
    ]
