# Generated by Django 5.1.5 on 2025-02-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_admin', '0002_rename_assigned_rfid_product_assign_rfid'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='database_ad_categor_193b31_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='assign_rfid',
            new_name='assigned_rfid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
    ]
