# Generated by Django 5.1.5 on 2025-02-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_admin', '0004_product_user_rfidentry_user_stockmovement_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
