# Generated by Django 5.1.5 on 2025-02-11 11:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_admin', '0005_remove_product_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='rfidentry',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='assigned_rfid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database_admin.rfidentry'),
        ),
        migrations.AlterField(
            model_name='rfidentry',
            name='status',
            field=models.CharField(choices=[('NONE', 'None'), ('ASSIGNED', 'Assigned'), ('NOT ASSIGNED', 'Not Assigned')], default='NOT ASSIGNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='rfidentry',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
