# Generated by Django 5.1.5 on 2025-02-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_admin', '0008_alter_product_assigned_rfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidentry',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('NOT ASSIGNED', 'Not Assigned')], default='NOT ASSIGNED', max_length=20),
        ),
    ]
