# Generated by Django 5.1.5 on 2025-02-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_admin', '0009_alter_rfidentry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidentry',
            name='status',
            field=models.CharField(choices=[('Not Assigned', 'Not Assigned'), ('Assigned', 'Assigned')], default='Not Assigned', max_length=20),
        ),
    ]
