# Generated by Django 5.1.5 on 2025-02-12 16:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_admin', '0011_rfidentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='rfid_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_admin.rfidentry', to_field='rfid_tag'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='timestamp_in',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='timestamp_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
