# Generated by Django 5.1.5 on 2025-02-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_admin', '0012_alter_stockmovement_rfid_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='timestamp_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='timestamp_out',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
