# Generated by Django 5.1.5 on 2025-02-12 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_admin', '0014_alter_stockmovement_timestamp_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfidentry',
            old_name='id',
            new_name='sno',
        ),
    ]
