# Generated by Django 5.1.5 on 2025-02-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_admin', '0015_rename_id_rfidentry_sno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfidentry',
            old_name='sno',
            new_name='id',
        ),
    ]
