# Generated by Django 5.1.5 on 2025-02-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_admin', '0016_rename_sno_rfidentry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
