# Generated by Django 5.1.5 on 2025-02-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_admin', '0017_alter_rfidentry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='rfid_tag',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
