# Generated by Django 5.1.5 on 2025-02-12 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_admin', '0018_alter_stockmovement_rfid_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='rfid_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_admin.rfidentry', to_field='rfid_tag'),
        ),
    ]
