# Generated by Django 5.1.5 on 2025-03-10 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_admin', '0019_alter_stockmovement_rfid_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='action',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='rfid_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_admin.rfidentry'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='timestamp_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
